export  const USER_SIGN_UP_REQUEST = "USER_SIGN_UP_REQUEST";
export  const USER_SIGN_UP_SUCCESS = "USER_SIGN_UP_SUCCESS";
export  const USER_SIGN_UP_FAIL = "USER_SIGN_UP_FAIL";


export  const USER_LOG_IN_REQUEST = "USER_LOG_IN_REQUEST";
export  const USER_LOG_IN_SUCCESS = "USER_LOG_IN_SUCCESS";
export  const USER_LOG_IN_FAIL = "USER_LOG_IN_FAIL";


export const USER_LOG_IN = "USER_LOG_IN";

export const USER_UPSERT = "USER_UPSERT";

export const USER_UPSERT_REQUEST = "USER_UPSERT_REQUEST";
export const USER_UPSERT_SUCCESS = "USER_UPSERT_SUCCESS";
export const USER_UPSERT_FAIL = "USER_UPSERT_FAIL";



export const NEW_GOOD_REQUEST = "NEW_GOOD_REQUEST";
export const NEW_GOOD_SUCCESS = "NEW_GOOD_SUCCESS";
export const NEW_GOOD_FAIL = "NEW_GOOD_FAIL";

export const NEW_CATEGORY_REQUEST = "NEW_CATEGORY_REQUEST";
export const NEW_CATEGORY_SUCCESS = "NEW_CATEGORY_SUCCESS";
export const NEW_CATEGORY_FAIL = "NEW_CATEGORY_FAIL";

export const GET_OWN_PHOTOS_REQUEST = "GET_OWN_PHOTOS_REQUEST";
export const GET_OWN_PHOTOS_SUCCESS = "GET_OWN_PHOTOS_SUCCESS";
export const GET_OWN_PHOTOS_FAIL = "GET_OWN_PHOTOS_FAIL";


export const GET_USERS_GOODS_REQUEST = "GET_USERS_GOODS_REQUEST";
export const GET_USERS_GOODS_SUCCESS = "GET_USERS_GOODS_SUCCESS";
export const GET_USERS_GOODS_FAIL = "GET_USERS_GOODS_FAIL";


