export  const USER_SIGN_UP_REQUEST = "USER_SIGN_UP_REQUEST";
export  const USER_SIGN_UP_SUCCESS = "USER_SIGN_UP_SUCCESS";
export  const USER_SIGN_UP_FAIL = "USER_SIGN_UP_FAIL";


export  const USER_LOG_IN_REQUEST = "USER_LOG_IN_REQUEST";
export  const USER_LOG_IN_SUCCESS = "USER_LOG_IN_SUCCESS";
export  const USER_LOG_IN_FAIL = "USER_LOG_IN_FAIL";


export const USER_LOG_IN = "USER_LOG_IN";
export const AUTO_LOG_IN = "AUTO_LOG_IN"
export const USER_UPSERT = "USER_UPSERT";
export const LOG_OUT_USER = "LOG_OUT_USER"

// export const USER_UPSERT_REQUEST = "USER_UPSERT_REQUEST";
// export const USER_UPSERT_SUCCESS = "USER_UPSERT_SUCCESS";
// export const USER_UPSERT_FAIL = "USER_UPSERT_FAIL";



export const NEW_GOOD_REQUEST = "NEW_GOOD_REQUEST";
export const NEW_GOOD_SUCCESS = "NEW_GOOD_SUCCESS";
export const NEW_GOOD_FAIL = "NEW_GOOD_FAIL";

export const NEW_CATEGORY_REQUEST = "NEW_CATEGORY_REQUEST";
export const NEW_CATEGORY_SUCCESS = "NEW_CATEGORY_SUCCESS";
export const NEW_CATEGORY_FAIL = "NEW_CATEGORY_FAIL";

export const GET_OWN_PHOTOS_REQUEST = "GET_OWN_PHOTOS_REQUEST";
export const GET_OWN_PHOTOS_SUCCESS = "GET_OWN_PHOTOS_SUCCESS";
export const GET_OWN_PHOTOS_FAIL = "GET_OWN_PHOTOS_FAIL";


export const GET_USERS_GOODS_REQUEST = "GET_USERS_GOODS_REQUEST";
export const GET_USERS_GOODS_SUCCESS = "GET_USERS_GOODS_SUCCESS";
export const GET_USERS_GOODS_FAIL = "GET_USERS_GOODS_FAIL";


export const GET_ALL_CATEGORIES_REQUEST = "GET_ALL_CATEGORIES_REQUEST";
export const GET_ALL_CATEGORIES_SUCCESS = "GET_ALL_CATEGORIES_SUCCESS";
export const GET_ALL_CATEGORIES_FAIL = "GET_ALL_CATEGORIES_FAIL";

export const GET_ALL_ORDERS_REQUEST = "GET_ALL_ORDERS_REQUEST";
export const GET_ALL_ORDERS_SUCCESS = "GET_ALL_ORDERS_SUCCESS";
export const GET_ALL_ORDERS_FAIL = "GET_ALL_ORDERS_FAIL";


export const MAKE_ORDER_REQUEST = "MAKE_ORDER_REQUEST";
export const MAKE_ORDER_SUCCESS = "MAKE_ORDER_SUCCESS";
export const MAKE_ORDER_FAIL = "MAKE_ORDER_FAIL";

export const ADD_GOOD_IN_CART = "ADD_GOOD_IN_CART";
export const CLEAR_ARRAY_GOODS = "CLEAR_ARRAY_GOODS";

export const INC_COUNT_ITEM_CART = "INC_COUNT_ITEM_CART";
export const DEC_COUNT_ITEM_CART = "DEC_COUNT_ITEM_CART";
export const DEL_ONE_ITEM_FROM_CART = "DEL_ONE_ITEM_FROM_CART";








